# Generated by Django 4.0.5 on 2022-06-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='total',
        ),
    ]
