# Generated by Django 4.0.5 on 2022-06-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_quantity_inventory_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('-created_at',), 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='inventorygroup',
            options={'ordering': ('-created_at',), 'verbose_name': 'Inventory Group', 'verbose_name_plural': 'Inventory Groups'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',), 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ('-created_at',), 'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('-created_at',), 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterField(
            model_name='inventorygroup',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_relations', to='inventory.inventorygroup'),
        ),
    ]
